### ISSUE TITLE
rarchives.spambot doesnt overwrite the append.

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#11]
the new feature for adding links from spambot to blacklist.p doesnt overwrite existing changes.

it will add the same links every time resulting in some 5000 lines when much less are needed.

**Comment by jacobstein123** [comment]
This should be fixed now. It now checks against the blacklist after the domain is already formatted.

**Comment by tek0011** [comment]
Still happening.  After a few days of restarting the bot, the blacklist file is nearly 40,000 lines long

**Comment by jacobstein123** [comment]
Is this still occurring? Not sure why it shouldn't overwrite as it checks if the domain is in the blacklist before adding it.

**Comment by tek0011** [comment]
looks good
